# Generated by Django 5.1.1 on 2024-10-01 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitionId', models.CharField(max_length=20, verbose_name='Transition id')),
                ('voiceId', models.CharField(max_length=10, verbose_name='Voice Id')),
                ('campaignData', models.TextField(verbose_name='Campaign Numbers')),
                ('obd_type', models.CharField(choices=[('SINGLE_VOICE', 'SINGLE VOICE'), ('DTMF', 'DTMF'), ('CallPatch', 'Call Patch')], default='SINGLE_VOICE', max_length=12, verbose_name='OBD Type')),
                ('dtmf', models.CharField(blank=True, max_length=10, verbose_name='DTMF?')),
                ('call_patch_no', models.CharField(blank=True, max_length=20, verbose_name='Call Patch No')),
                ('err_code', models.CharField(blank=True, max_length=10, verbose_name='Error Code')),
                ('err_desc', models.CharField(blank=True, max_length=100, verbose_name='Error Description')),
                ('campg_id', models.CharField(blank=True, max_length=20, verbose_name='Campaign ID')),
                ('trans_id', models.CharField(blank=True, max_length=30, verbose_name='Transaction ID')),
                ('status_fetched', models.BooleanField(default=False, verbose_name='is_feteched?')),
                ('sms_required', models.BooleanField(default=False, verbose_name='sent sms on answered?')),
            ],
        ),
        migrations.CreateModel(
            name='SingleVoiceCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transitionId', models.CharField(max_length=20, verbose_name='Transition id')),
                ('voiceId', models.CharField(max_length=10, verbose_name='Voice Id')),
                ('dn', models.CharField(max_length=10, verbose_name='Destination Number')),
                ('obd_type', models.CharField(choices=[('SINGLE_VOICE', 'SINGLE VOICE'), ('DTMF', 'DTMF'), ('CallPatch', 'Call Patch')], default='SINGLE_VOICE', max_length=12, verbose_name='OBD Type')),
                ('dtmf', models.CharField(blank=True, max_length=10, verbose_name='DTMF?')),
                ('call_patch_no', models.CharField(blank=True, max_length=20, verbose_name='Call Patch No')),
                ('err_code', models.CharField(blank=True, max_length=10, verbose_name='Error Code')),
                ('err_desc', models.CharField(blank=True, max_length=100, verbose_name='Error Description')),
                ('campg_id', models.CharField(blank=True, max_length=20, verbose_name='Campaign ID')),
                ('trans_id', models.CharField(blank=True, max_length=30, verbose_name='Transaction ID')),
                ('status_fetched', models.BooleanField(default=False, verbose_name='is_feteched?')),
                ('sms_required', models.BooleanField(default=False, verbose_name='sent sms on answered?')),
            ],
        ),
        migrations.CreateModel(
            name='VoxUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantype', models.IntegerField(default=15, verbose_name='Plan Type')),
                ('filename', models.CharField(max_length=40, verbose_name='Filename')),
                ('uploadedfile', models.FileField(upload_to='voxupload', verbose_name='Uploaded file')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('voiceid', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStatus',
            fields=[
                ('campaignCode', models.CharField(blank=True, max_length=30, verbose_name='CampaignCode')),
                ('campaignName', models.CharField(blank=True, max_length=30, verbose_name='Campaign Name')),
                ('campaignScheduleTime', models.CharField(max_length=30, verbose_name='Campaign Schedule Time')),
                ('scheduleType', models.CharField(blank=True, max_length=30)),
                ('enddate', models.CharField(blank=True, max_length=30, verbose_name='EndDate')),
                ('msisdn', models.CharField(max_length=10)),
                ('cli', models.CharField(max_length=10)),
                ('flag', models.CharField(max_length=2)),
                ('status', models.CharField(max_length=30)),
                ('starttime', models.DateTimeField(verbose_name='START TIME')),
                ('endtime', models.DateTimeField(verbose_name='END TIME')),
                ('valid_dn', models.CharField(blank=True, max_length=20)),
                ('invalid_dn', models.CharField(blank=True, max_length=20)),
                ('error', models.CharField(blank=True, max_length=30)),
                ('duration', models.IntegerField()),
                ('projected_amount', models.CharField(blank=True, max_length=20)),
                ('consumed_amount', models.CharField(blank=True, max_length=20)),
                ('opening_balance', models.CharField(blank=True, max_length=20)),
                ('closing_balance', models.CharField(blank=True, max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=20)),
                ('dtmf', models.CharField(blank=True, max_length=20)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('campaignId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartping.campaigncreation')),
            ],
        ),
    ]
