# Generated by Django 5.1.1 on 2024-10-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstatus',
            name='c_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='campaignstatus',
            name='sms_required',
            field=models.BooleanField(default=False),
        ),
    ]
