# Generated by Django 5.1.1 on 2024-10-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0002_campaignstatus_c_status_campaignstatus_sms_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstatus',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
