# Generated by Django 5.1.1 on 2024-10-03 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0003_campaignstatus_sms_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigncreation',
            name='trans_id',
        ),
    ]
