# Generated by Django 5.1.1 on 2024-10-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0004_remove_campaigncreation_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='is sent?'),
        ),
        migrations.AlterField(
            model_name='campaigncreation',
            name='campaignData',
            field=models.FileField(upload_to='uploads/campaign_data', verbose_name='Campaign Numbers'),
        ),
    ]
