# Generated by Django 5.1.1 on 2024-10-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0005_campaigncreation_is_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncreation',
            name='campg_id',
            field=models.TextField(blank=True, verbose_name='Campaign ID'),
        ),
    ]
