# Generated by Django 5.1.1 on 2024-10-04 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0006_alter_campaigncreation_campg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaigncreation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='campaigncreation',
            name='campg_id',
            field=models.TextField(blank=True, verbose_name='Campaign IDs'),
        ),
    ]
