# Generated by Django 5.1.1 on 2025-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0008_voxupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voxupload',
            name='processedfile',
            field=models.FileField(blank=True, null=True, upload_to='voxupload', verbose_name='Processed file'),
        ),
    ]
