# Generated by Django 5.1.1 on 2025-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0009_voxupload_processedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voxupload',
            name='plantype',
            field=models.IntegerField(choices=[(15, '15'), (30, '30'), (60, '60'), (120, '120')], default=15, verbose_name='Plan Type'),
        ),
    ]
