# Generated by Django 5.1.1 on 2025-03-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0011_alter_campaigncreation_voiceid_and_more'),
        ('smscampaign', '0003_smsreport_sms_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlevoicecreation',
            name='call_patch_no',
        ),
        migrations.RemoveField(
            model_name='singlevoicecreation',
            name='dtmf',
        ),
        migrations.RemoveField(
            model_name='singlevoicecreation',
            name='transitionId',
        ),
        migrations.AddField(
            model_name='campaigncreation',
            name='duration',
            field=models.IntegerField(default=0, help_text='Minimum duration to qualify for SMS', verbose_name='Minimum Duration'),
        ),
        migrations.AddField(
            model_name='campaigncreation',
            name='sms_template',
            field=models.ForeignKey(blank=True, help_text='Verified sms only', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smscampaign.smstemplate'),
        ),
        migrations.AddField(
            model_name='singlevoicecreation',
            name='duration',
            field=models.IntegerField(default=0, help_text='Minimum duration to qualify for SMS', verbose_name='Minimum Duration'),
        ),
        migrations.AddField(
            model_name='singlevoicecreation',
            name='sms_template',
            field=models.ForeignKey(blank=True, help_text='Verified sms only', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='smscampaign.smstemplate'),
        ),
    ]
