# Generated by Django 5.1.1 on 2025-03-19 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0012_remove_singlevoicecreation_call_patch_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlevoicecreation',
            name='voiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smartping.voxupload', to_field='voiceid'),
        ),
    ]
