# Generated by Django 5.1.1 on 2025-03-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0014_campaigncreation_user_singlevoicecreation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='invalid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaigncreation',
            name='valid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaigncreation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='campaigncreation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
