# Generated by Django 5.1.1 on 2025-03-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0015_campaigncreation_invalid_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='processedData',
            field=models.FileField(blank=True, upload_to='uploads/valid_campaign_data', verbose_name='Valid Base'),
        ),
    ]
