# Generated by Django 5.1.1 on 2025-03-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0016_campaigncreation_processeddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigncreation',
            name='voiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartping.voxupload', to_field='voiceid'),
        ),
        migrations.AlterField(
            model_name='singlevoicecreation',
            name='voiceId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartping.voxupload', to_field='voiceid'),
        ),
    ]
