# Generated by Django 5.1.1 on 2025-04-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0017_alter_campaigncreation_voiceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='status',
            field=models.CharField(default='processing', max_length=15),
        ),
        migrations.AddField(
            model_name='singlevoicecreation',
            name='status',
            field=models.CharField(default='processing', max_length=15),
        ),
    ]
