# Generated by Django 5.1.1 on 2025-04-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0018_campaigncreation_status_singlevoicecreation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlevoicecreation',
            name='dtmf',
            field=models.CharField(default='NA', max_length=2, verbose_name='DTMF?'),
        ),
    ]
