# Generated by Django 5.1.1 on 2025-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0019_singlevoicecreation_dtmf'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigncreation',
            name='reportData',
            field=models.FileField(blank=True, upload_to='reports', verbose_name='Report Data'),
        ),
        migrations.AddField(
            model_name='campaigncreation',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='Sms Sent?'),
        ),
    ]
