# Generated by Django 5.1.1 on 2025-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartping', '0020_campaigncreation_reportdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voxupload',
            name='voiceid',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
