# Generated by Django 5.1.1 on 2025-03-17 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KannelSMSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Provider Name')),
                ('host', models.URLField()),
                ('port', models.IntegerField(default=14013)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('smsc', models.CharField(max_length=50)),
                ('is_https', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('header', models.CharField(max_length=6, verbose_name='SMS HEADER')),
                ('pe_id', models.CharField(max_length=20, verbose_name='Personal Entity ID')),
                ('message', models.TextField(help_text='Approved Message Content', verbose_name='Message Content')),
                ('template_id', models.CharField(max_length=20, verbose_name='Template ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('test_status', models.CharField(choices=[('na', 'Not Available'), ('sent', 'Sent'), ('failed', 'Failed'), ('delvrd', 'Delivered'), ('reject', 'Rejected')], default='na', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmsReport',
            fields=[
                ('track_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent?')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Delivered?')),
                ('msg_status', models.CharField(max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sms_test_reports', to=settings.AUTH_USER_MODEL)),
                ('smstemplate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smscampaign.smstemplate')),
            ],
        ),
    ]
