# Generated by Django 5.1.1 on 2025-03-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smscampaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsreport',
            name='smstemplate',
        ),
        migrations.AddField(
            model_name='smsreport',
            name='header',
            field=models.CharField(default='NA', max_length=6, verbose_name='SMS HEADER'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsreport',
            name='message',
            field=models.TextField(default='NA', help_text='Approved Message Content', verbose_name='Message Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsreport',
            name='pe_id',
            field=models.CharField(default='NA', max_length=20, verbose_name='Personal Entity ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsreport',
            name='template_id',
            field=models.CharField(default='NA', max_length=20, verbose_name='Template ID'),
            preserve_default=False,
        ),
    ]
