# Generated by Django 5.1.1 on 2025-03-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smscampaign', '0002_remove_smsreport_smstemplate_smsreport_header_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsreport',
            name='sms_route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='smscampaign.kannelsmsc'),
        ),
    ]
