# Generated by Django 5.1.1 on 2025-07-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smscampaign', '0003_smsreport_sms_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsreport',
            name='sms_type',
            field=models.CharField(choices=[('approve', 'Approval'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
