# Generated by Django 5.1.1 on 2025-03-26 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voiceid', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('filetype', models.CharField(default='promo', max_length=20)),
                ('uploadedfile', models.FileField(upload_to='alertbox_media')),
                ('processed_file', models.FileField(blank=True, upload_to='alertbox_media')),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='approved', max_length=10)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
