# Generated by Django 5.1.1 on 2025-03-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicetemplate',
            name='status',
            field=models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='pending', max_length=10),
        ),
    ]
