# Generated by Django 5.1.1 on 2025-04-12 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertbox', '0002_alter_voicetemplate_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voiceid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('filename', models.FileField(upload_to='voicecampaign')),
                ('reports', models.FileField(blank=True, upload_to='voicecampaign_report')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('running', 'RUNNING'), ('completed', 'COMPLETED')], default='pending', max_length=10)),
                ('user', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
